version: 2
jobs:
  test:
    docker:
      - image: docker:18.06.3-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run: |
         docker build -t lua-resty-woothee:$CIRCLE_SHA1 .
         docker run lua-resty-woothee:$CIRCLE_SHA1 sh -c 'make all'
workflows:
  version: 2
  test:
    jobs:
      - test
